### ISSUE TITLE
[Question] Form upload vuln?

### ISSUE THREAD

**Issue by DeadPackets** [ineffyble/pleasepet#31]
I cant check right now since I got rate-limited by the server xD But did you check if the pictures or sounds being uploaded are actually pictures and not shells? (Although i know that the ruby interpreter would probably not understand PHP shells but still)

[Oh and if you read server logs, sorry for attempting to scan the website with a vuln scanner xD, just trying to be helpful]

**Comment by ineffyble** [comment]
Hey, yes :) the paperclip gem handles file management, and if you look in app/models you'll see both fields have type validation set
